# Defining and running multi-container Docker application
version: '3'

services:  
   # mariadb  
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        - DB_NAME=wordpress
        - DB_HOST_PWD=hostpassword
        - DB_USER=wp_user
        - DB_USER_PWD=userpassword
        - DB_HOST=mariadb
    image: mariadb:v_1
    env_file:  
      - ./.env
    volumes:
      - mariadb-v:/var/lib/mysql
    restart: always
    networks:
      - inception

  # Nginx Service
  nginx:
    container_name: nginx
    depends_on: 
      - wordpress
    build: ./requirements/nginx
    image: nginx:v_1
    command: nginx -g "daemon off;"
    ports:
      - 443:443 
    links:
      - wordpress
    volumes:
      - wordpress-v:/var/www/website 
    restart: always
    networks: 
      - inception

  # wordpress  
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress:v_1
    volumes:
      - wordpress-v:/var/www/website
    links:
      - mariadb
    restart: always
    networks:
      - inception
  

networks:
  inception:
    driver: bridge    

volumes:
  mariadb-v:
    driver: local
    driver_opts:
       type: 'none'
       o: 'bind'
       device: /home/xuwang/data/mariadb-v
  wordpress-v:
    driver: local
    driver_opts:
       type: 'none'
       o: 'bind'
       device: /home/xuwang/data/wordpress-v

  
